### ISSUE TITLE
wrong raven-clj version reported to sentry

### ISSUE THREAD

**Issue by schmir** [sethtrain/raven-clj#18]
I'm using raven-clj 1.4.3. In sentry's Detail View under "SDK" the version is reported as 1.4.2.
I guess raven-clj.core/sentry-client probably has to be updated (along with some tests, and maybe project.clj)

**Comment by martinklepsch** [comment]
I think this has been fixed with 1.5.0 and I just cut 1.5.2 (supporting secret-less DSNs) and replaced all version strings I could find 👍
