### ISSUE TITLE
Body/params is never populated

### ISSUE THREAD

**Issue by andrewnguyenism** [sethtrain/raven-clj#19]
![image](https://cloud.githubusercontent.com/assets/388693/18976963/b060aeb4-86f9-11e6-9cfb-d8e104e386cf.png)

Viewing issues for my Clojure projects on Sentry, the "Body" section always shows `{}`. It seems like its not capturing the request params at all for some reason? The other sections - "Cookies", "Headers" - are filling correctly (although I do have the issue in #15 for sessions).

**Comment by minimal** [comment]
Looks like it just get `:params` which is already handled by `:query-string`, it should probably get `:body` instead.

https://github.com/sethtrain/raven-clj/blob/63aa06464ed71ec60dd8761301e1b97100d833c0/src/raven_clj/interfaces.clj#L17

**Comment by andrewnguyenism** [comment]
```
;; If you want to fully utilize the Http interface you should make sure
;; you use the wrap-params and wrap-keyword-params middlewares to ensure
;; the request data is stored correctly.
```

Me not reading the manual close enough...
