### ISSUE TITLE
Include ex-data in GetSentry report for the ring wrapper

### ISSUE THREAD

**Issue by khiemlam** [sethtrain/raven-clj#20]
Our team has added a feature to include the ex-data in the GetSentry report as an `extra` parameter in the ring wrapper.  I was wondering if this is a feature that would be valuable in the core project.  If it is, happy to spin up a PR with the changes.  It would look something like [this commit](https://github.com/reifyhealth/raven-clj/commit/834219e1936f98f96e9441a17d50fea721263619) without our team's specific configuration.  Happy to discuss and adjust the PR as needed.  Thanks!

**Comment by cldwalker** [comment]
@martinklepsch Assuming you're one of the maintainers, any thoughts on this? We'd love to contribute if possible

**Comment by martinklepsch** [comment]
Thanks for pinging again, this seems like a reasonable addition. Happy to take a PR. Didn't look at the commit now (on mobile) but I'm sure it'll be fine 👍

**Comment by khiemlam** [comment]
@martinklepsch Great!  I created this PR https://github.com/sethtrain/raven-clj/pull/21.  Let me know if you have any questions or comments.  Happy to modify as needed.

**Comment by martinklepsch** [comment]
Closing in favor of #21
